default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nashthedev
  database: dis_website_development
  password: <%= ENV["DIS_WEBSITE_DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: dis_website_development

test:
  <<: *default
  database: dis_website_test

production:
  <<: *default
  database: dis_website_production
  username: dis_website
  password: <%= ENV["DIS_WEBSITE_DATABASE_PASSWORD"] %>
