default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DIS_WEBSITE_DATABASE_USERNAME"] %>
  database: dis_website_development
  password: <%= ENV["DIS_WEBSITE_DATABASE_PASSWORD"] %>
  host: localhost


development:
  <<: *default
  database: dis_website_development

test:
  <<: *default
  database: dis_website_test

production:
  <<: *default
  database: dis_website_production
  username: nashthedev
  password: <%= ENV["DIS_WEBSITE_DATABASE_PASSWORD"] %>
